### `Numpy-Array Manipulation`

In [1]:
import numpy as np

In [5]:
x = np.arange(1,13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
reshap_x = x.reshape(6,2)
reshap_x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
resize_x = np.resize(x, (6,2))
print(resize_x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [8]:
resize_x.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
resize_x.base is x

False

In [10]:
resize_x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
reshap_x.transpose()

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [12]:
reshap_x.T

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

### Join Array

In [20]:
x = np.arange(0,6).reshape(2,3)
y = np.arange(6,12).reshape(2,3)
print('x:\n',x,'\n')
print('y:\n',y,'\n')

con_ax0 = np.concatenate((x,y))
print('concatenate with axis = 0')
print(con_ax0,'\n')

con_ax1 = np.concatenate((x,y), axis=1)
print('concatenate with axis = 1')
print(con_ax1)

x:
 [[0 1 2]
 [3 4 5]] 

y:
 [[ 6  7  8]
 [ 9 10 11]] 

concatenate with axis = 0
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

concatenate with axis = 1
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [22]:
print('x:\n',x,'\n')
print('y:\n',y,'\n')

x:
 [[0 1 2]
 [3 4 5]] 

y:
 [[ 6  7  8]
 [ 9 10 11]] 



In [26]:
st_ax0 = np.stack((x,y))
st_ax1 = np.stack((x,y),axis=1)
print("stack with axis = 0\n")
print(st_ax0)
print("Shape = ",st_ax0.shape)
print("\nstack with axis = 1\n")
print(st_ax1)
print("Shape = ",st_ax1.shape)

stack with axis = 0

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape =  (2, 2, 3)

stack with axis = 1

[[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]]
Shape =  (2, 2, 3)


## Add/Remove Array Elements

In [27]:
x = np.arange(0,12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.insert(x, 3, 88)

array([ 0,  1,  2, 88,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
rx = x.reshape(4,3)
rx

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.insert(rx, 1, 88)

array([ 0, 88,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
np.insert(rx, 1, 88, axis=0)

array([[ 0,  1,  2],
       [88, 88, 88],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
np.insert(rx, 1, 88, axis=1)

array([[ 0, 88,  1,  2],
       [ 3, 88,  4,  5],
       [ 6, 88,  7,  8],
       [ 9, 88, 10, 11]])

In [38]:
x = np.arange(0,12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
np.delete(x, 1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
rx = x.reshape(4,3)
rx

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
np.delete(rx, 1,axis=0)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
np.delete(rx, 1,axis=1)

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [45]:
np.delete(rx,1)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])