In [1]:
import numpy as np

In [2]:
x = np.arange(0,12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
x[0,2] = -9
print(x)

[[ 0  1 -9]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
x[1] = 8
print(x)

[[ 0  1 -9]
 [ 8  8  8]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
x[:,0:2]

array([[ 0,  1],
       [ 8,  8],
       [ 6,  7],
       [ 9, 10]])

In [10]:
x = np.arange(0,20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
x[0:4:2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [15]:
x[-3:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
x[:-3]

array([[0, 1, 2, 3, 4]])

In [18]:
x = np.arange(0,12).reshape(2,3,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [19]:
x[0,0:2,]

array([[0, 1],
       [2, 3]])

## Advanced Indexing

Use Integer Indexing to select arbitrary items in each dimensions.

In [20]:
x = np.arange(0,20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
y = x[:-2, 1:3]
y

array([[1, 2],
       [6, 7]])

In [21]:
x[ [0,1] ]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
x[ [0,1], [1,3] ]

array([1, 8])

In [24]:
x[ [[1,1], [3,3],[0,2]], [[1,2],[1,2],[2,3]] ]

array([[ 6,  7],
       [16, 17],
       [ 2, 13]])