In [4]:
import numpy as np

In [5]:
scores = np.array([
    [75,80,85],
    [85,80,75],
    [80,85,90],
    [90,85,80],
    [70,80,90]
])
print(scores)

[[75 80 85]
 [85 80 75]
 [80 85 90]
 [90 85 80]
 [70 80 90]]


In [5]:
print(np.min(scores, axis=0))
print(np.min(scores, axis=1))

[70 80 75]
[75 75 80 80 70]


In [6]:
print(np.max(scores, axis=0))
print(np.max(scores, axis=1))

[90 85 90]
[85 85 90 90 90]


In [7]:
print(np.mean(scores, axis=0))
print(np.mean(scores, axis=1))

[80. 82. 84.]
[80. 80. 85. 85. 80.]


In [8]:
print(np.sum(scores, axis=1))

[240 240 255 255 240]


In [11]:
x = np.arange(-5,5)
print('x:',x)

y = 2*x + 10
print('y:',y)

x: [-5 -4 -3 -2 -1  0  1  2  3  4]
y: [ 0  2  4  6  8 10 12 14 16 18]


### Sorting and Filtering/Searching

In [6]:
scores

array([[75, 80, 85],
       [85, 80, 75],
       [80, 85, 90],
       [90, 85, 80],
       [70, 80, 90]])

In [7]:
# Ascending sort
print(np.sort(scores, axis=0),'\n')
print(np.sort(scores, axis=1))

[[70 80 75]
 [75 80 80]
 [80 80 85]
 [85 85 90]
 [90 85 90]] 

[[75 80 85]
 [75 80 85]
 [80 85 90]
 [80 85 90]
 [70 80 90]]


In [15]:
# Descending sort
print(-(np.sort(-scores, axis=1)))

[[85 80 75]
 [85 80 75]
 [90 85 80]
 [90 85 80]
 [90 80 70]]


In [19]:
#Create cuntomer data type
customer_dtype = np.dtype([('cid',str,10),('name', str,30),('age',np.int8)])

# Create customer records
cust_list = [('C100', 'David',35), ('C200','Stave',22), ('C300',"John",55)]

# Create NumPy array
customers = np.array(cust_list,customer_dtype)

print(customers)

[('C100', 'David', 35) ('C200', 'Stave', 22) ('C300', 'John', 55)]


In [21]:
print(np.sort(customers, order='age'))

[('C200', 'Stave', 22) ('C100', 'David', 35) ('C300', 'John', 55)]


In [22]:
print(np.sort(customers, order='age')[::-1])

[('C300', 'John', 55) ('C100', 'David', 35) ('C200', 'Stave', 22)]
