## Numpy- Basic Operation
Vectorization

In [1]:
import numpy as np

In [5]:
x = np.arange(0,5)
y = np.arange(5,10)
print('x:\n',x,'\n')
print('y:\n',y,'\n')

print(x+y)

x:
 [0 1 2 3 4] 

y:
 [5 6 7 8 9] 

[ 5  7  9 11 13]


In [12]:
x = np.arange(0,5)
y = np.arange(5,6)
print('x:\n',x)
print('x.shape = ',x.shape,'\n')
print('y:\n',y)
print('y.shape = ',y.shape,'\n')

print(x+y)

x:
 [0 1 2 3 4]
x.shape =  (5,) 

y:
 [5]
y.shape =  (1,) 

[5 6 7 8 9]


Numpy Operation on arrays with Compatible dimensions

In [15]:
x = np.arange(0,5)
y = np.array([10])
print('x:\n',x)
print('x.shape = ',x.shape,'\n')
print('y:\n',y)
print('y.shape = ',y.shape,'\n')
print('x*y =', x*y)

x:
 [0 1 2 3 4]
x.shape =  (5,) 

y:
 [10]
y.shape =  (1,) 

x*y = [ 0 10 20 30 40]


In [18]:
x = np.arange(0,12).reshape(2,6)
y = np.arange(0,6).reshape(1,6)
print('x:\n',x)
print('x.shape = ',x.shape,'\n')
print('y:\n',y)
print('y.shape = ',y.shape,'\n')
print('x*y =', x*y)

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
x.shape =  (2, 6) 

y:
 [[0 1 2 3 4 5]]
y.shape =  (1, 6) 

x*y = [[ 0  1  4  9 16 25]
 [ 0  7 16 27 40 55]]


In [20]:
x = np.arange(0,18).reshape(2,3,3)
y = np.arange(0,6).reshape(2,3,1)

print('x:\n',x)
print('x.shape = ',x.shape,'\n')
print('y:\n',y)
print('y.shape = ',y.shape,'\n')

print('x*y =', x*y)

x:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
x.shape =  (2, 3, 3) 

y:
 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
y.shape =  (2, 3, 1) 

x*y = [[[ 0  0  0]
  [ 3  4  5]
  [12 14 16]]

 [[27 30 33]
  [48 52 56]
  [75 80 85]]]
