In [2]:
import numpy as np

In [19]:
size = 500000

x = np.arange(0, size)
y = np.arange(0, size)

#Magic cammand
%timeit -n5 x * y

1.69 ms ± 270 µs per loop (mean ± std. dev. of 7 runs, 5 loops each)


In [22]:
lx = list(range(0,size))
ly = list(range(0,size))

%timeit -n5 [lx[i] * ly[i] for i in range(0,size)]

85.6 ms ± 1.77 ms per loop (mean ± std. dev. of 7 runs, 5 loops each)


In [25]:
%timeit -n5 list( map(lambda x,y: x*y,lx,ly) )

96.4 ms ± 3.12 ms per loop (mean ± std. dev. of 7 runs, 5 loops each)


## Numpy Array

In [4]:
import numpy as np

x = np.array([10,20,30,40,50,60,70,80])

print(x)
print("dtype =", x.dtype)
print("item size =", x.dtype.itemsize)
print("item x[0] =", x[0])
print("type of item x[0] =", type(x[0]))

[10 20 30 40 50 60 70 80]
dtype = int32
item size = 4
item x[0] = 10
type of item x[0] = <class 'numpy.int32'>


In [5]:
x = np.array([10,20,30,40,50,60,70,80], np.float64)

print(x)
print("dtype =", x.dtype)
print("item size =", x.dtype.itemsize)
print("item x[0] =", x[0])
print("type of item x[0] =", type(x[0]))

[10. 20. 30. 40. 50. 60. 70. 80.]
dtype = float64
item size = 8
item x[0] = 10.0
type of item x[0] = <class 'numpy.float64'>


In [11]:
# Define customer structure dtype
customer_dtype = np.dtype([("cid", np.str_,10), ('name', str, 30), ('age', np.int8)])

# Customer records
cust_list = [('C100', "David", 25), ('C200', 'Phil', 30), ('C300', 'Stave', 35)]

# Create customer_dtype ndarray
customers = np.array(cust_list, customer_dtype)

print(customers)
print(customers[0])
print(customers["name"])
print(customers[customers['age'] > 30])

[('C100', 'David', 25) ('C200', 'Phil', 30) ('C300', 'Stave', 35)]
('C100', 'David', 25)
['David' 'Phil' 'Stave']
[('C300', 'Stave', 35)]


## Shape and Axis

In [20]:
x = np.array(range(1,13))
print(x)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [22]:
rx = x.reshape(3,4)
print(x)
print(rx)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
x[0] = 1
print(x)
print(rx)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
rx = x.reshape(3,4).copy()

x[0] = 500
print(x)
print(rx)

[500   2   3   4   5   6   7   8   9  10  11  12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
# Order = 'C -> row-major order
x = np.array(range(1,13)).reshape(3,4, order='C')
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
# Order = 'F' -> column-major order
x = np.array(range(1,13)).reshape(3,4, order='F')
print(x)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [38]:
x = np.array([[1,2,3],[4,5,6]])

print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [43]:
print(x,'\n')
print('np.sum(x, axis=0) = ',np.sum(x, axis=0))
print('np.sum(x, axis=1) = ',np.sum(x, axis=1))

[[1 2 3]
 [4 5 6]] 

np.sum(x, axis=0) =  [5 7 9]
np.sum(x, axis=1) =  [ 6 15]


In [50]:
x = np.array([ [ [1,2,3],[4,5,6] ],[ [7,8,9], [10,11,12] ] ])
print(x)
print(x.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [53]:
x = np.array([ [1,2,3], [4,5,6], [7,8] ])

C:\Users\helio\AppData\Local\Temp\ipykernel_12932\918823306.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([ [1,2,3], [4,5,6], [7,8] ])


In [56]:
x = np.array([ [1,2,3], [4,5,6], [7,8] ], dtype=object)
print(x)
print(x.shape)
print(x[0], type(x[0]))

[list([1, 2, 3]) list([4, 5, 6]) list([7, 8])]
(3,)
[1, 2, 3] <class 'list'>


In [58]:
x = np.arange(10,90,10,np.float64)
print(x)
print(x.shape)

[10. 20. 30. 40. 50. 60. 70. 80.]
(8,)


In [64]:
m = np.empty((3,2), dtype=int)
print(m)

[[ -720729728         531]
 [-1102188160         531]
 [ -720713536         531]]


In [69]:
m = np.zeros((3,2), dtype=int)
n = np.ones((3,2), dtype=int)
print(m)
print(n)

[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [75]:
x = np.array([[1,2], [4,5], [7,8]])
x.shape

(3, 2)