## Random Sampling

In [2]:
import numpy as np
from numpy.random import default_rng

In [3]:
# Create object of defualt random number generator
rng = default_rng()

# Random 5 float numbers from 0.0 to 1.0
rng.random(5)

array([0.22880916, 0.43915777, 0.23536176, 0.06099943, 0.1113748 ])

In [9]:
from numpy import random

random.rand(5)

array([0.84922227, 0.91790527, 0.05398659, 0.96137164, 0.96193194])

In [8]:
#seed = 2021
rng = default_rng(2021)

rng.random(50)

array([0.75694783, 0.94138187, 0.59246304, 0.31884171, 0.62607384,
       0.03551387, 0.25212696, 0.48501366, 0.30126688, 0.72195094,
       0.92989066, 0.90823581, 0.08495856, 0.27036617, 0.97168176,
       0.26015007, 0.80052031, 0.79827865, 0.6425692 , 0.66806864,
       0.23521315, 0.02190576, 0.12961145, 0.12298406, 0.45408739,
       0.47734517, 0.66692504, 0.80072716, 0.42069822, 0.11445225,
       0.25617877, 0.48995179, 0.08528271, 0.7167631 , 0.33100379,
       0.61018338, 0.59819869, 0.82549985, 0.88627002, 0.85022632,
       0.52795471, 0.46057818, 0.02466648, 0.93499413, 0.33640568,
       0.13258264, 0.19667242, 0.3612112 , 0.23337686, 0.15231137])

In [11]:
#seed = 2021
rng = default_rng(2021)

rng.random(50)

array([0.75694783, 0.94138187, 0.59246304, 0.31884171, 0.62607384,
       0.03551387, 0.25212696, 0.48501366, 0.30126688, 0.72195094,
       0.92989066, 0.90823581, 0.08495856, 0.27036617, 0.97168176,
       0.26015007, 0.80052031, 0.79827865, 0.6425692 , 0.66806864,
       0.23521315, 0.02190576, 0.12961145, 0.12298406, 0.45408739,
       0.47734517, 0.66692504, 0.80072716, 0.42069822, 0.11445225,
       0.25617877, 0.48995179, 0.08528271, 0.7167631 , 0.33100379,
       0.61018338, 0.59819869, 0.82549985, 0.88627002, 0.85022632,
       0.52795471, 0.46057818, 0.02466648, 0.93499413, 0.33640568,
       0.13258264, 0.19667242, 0.3612112 , 0.23337686, 0.15231137])

### Basic Random Numbers

In [13]:
rng = default_rng()

rng.integers(low=0, high=10, endpoint=True,size=5)

array([4, 4, 2, 7, 5], dtype=int64)

In [14]:
rng.random(5)


array([0.12313632, 0.09056636, 0.04773914, 0.71628311, 0.90258507])

In [16]:
rng.random(10).reshape(2,5)

array([[0.33931547, 0.1529066 , 0.03185405, 0.85608422, 0.30265704],
       [0.29097189, 0.55056522, 0.13244043, 0.17069974, 0.2032011 ]])

In [17]:
int_ds = np.arange(0,150,3)
int_ds

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147])

In [19]:
rng.choice(int_ds, size=10)

array([138, 117,   0,   6, 117, 126,  60, 111,  27, 141])

In [20]:
rng.choice( int_ds, size=(5,2) )

array([[114,  90],
       [120,  45],
       [ 66,  60],
       [135,  15],
       [ 90, 135]])

In [21]:
int_ds2 = int_ds.reshape(5,10)
int_ds2

array([[  0,   3,   6,   9,  12,  15,  18,  21,  24,  27],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 60,  63,  66,  69,  72,  75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102, 105, 108, 111, 114, 117],
       [120, 123, 126, 129, 132, 135, 138, 141, 144, 147]])

In [39]:
x = rng.choice(int_ds2, size=(2,), axis=0)
print(x)
print('x.shape =',x.shape)

[[ 60  63  66  69  72  75  78  81  84  87]
 [ 90  93  96  99 102 105 108 111 114 117]]
x.shape = (2, 10)


In [42]:
x = rng.choice(int_ds2, size=(2,), axis=1)
print(x)
print('x.shape =',x.shape)

[[ 18  15]
 [ 48  45]
 [ 78  75]
 [108 105]
 [138 135]]
x.shape = (5, 2)


In [44]:
x = np.arange(0,10)
print(x,'\n')

rng = default_rng()
rng.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9] 

[8 0 5 9 3 2 4 7 1 6]


In [46]:
x = np.arange(0,12).reshape(3,4)
print(x ,'\n')

rng.shuffle(x, axis=0)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [47]:
x = np.arange(0,12).reshape(3,4)
print(x ,'\n')

rng.shuffle(x, axis=1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 3  0  2  1]
 [ 7  4  6  5]
 [11  8 10  9]]


In [48]:
x = np.arange(0,10)
print(x ,'\n')

pm = rng.permuted(x)
print(pm)

[0 1 2 3 4 5 6 7 8 9] 

[1 6 4 8 5 7 0 9 2 3]


In [49]:
x is pm

False